#!/usr/bin/env python3
"""M12.6: dependency license inventory, generated from `cargo license`'s
own JSON output (installed via `cargo install cargo-license`) -- never a
hand-maintained or invented classification. Writes
docs/LICENSE_INVENTORY.md (human-readable) and
target/dist/license-inventory.json (machine-readable, same shape
`checksums.py`'s own manifest.json uses: a schemaVersion, then a plain
list, no embedded timestamp, so two runs over an unchanged Cargo.lock
produce byte-identical inventory data).

Any dependency with an empty/missing license field is flagged EXPLICITLY,
never silently dropped from the report or silently assumed compatible --
this project's own "UNKNOWN != ZERO" discipline applied to license data."""
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]


def main():
    result = subprocess.run(
        ['cargo', 'license', '--json'], cwd=ROOT, capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(
            'cargo-license not found or failed; install with:\n'
            '  cargo install cargo-license --locked\n'
            f'stderr: {result.stderr}',
            file=sys.stderr,
        )
        sys.exit(1)
    deps = json.loads(result.stdout)
    unknown = [d for d in deps if not d.get('license')]
    entries = sorted(
        (
            {
                'name': d['name'],
                'version': d.get('version', ''),
                'license': d.get('license') or 'UNKNOWN',
                'repository': d.get('repository') or None,
            }
            for d in deps
        ),
        key=lambda e: e['name'],
    )

    dist = ROOT / 'target' / 'dist'
    dist.mkdir(parents=True, exist_ok=True)
    (dist / 'license-inventory.json').write_text(
        json.dumps(
            {'schemaVersion': 1, 'projectLicense': 'MIT OR Apache-2.0', 'dependencies': entries},
            indent=2,
        )
        + '\n'
    )

    lines = [
        '# SAUR-ON dependency license inventory',
        '',
        'Generated by `scripts/license_inventory.py` from `cargo license`\'s own',
        'output against the locked dependency graph (`Cargo.lock`) -- never',
        'hand-classified. Regenerate after any `Cargo.lock` change with:',
        '',
        '```sh',
        'cargo install cargo-license --locked   # once',
        'python3 scripts/license_inventory.py',
        '```',
        '',
        f'**Project license**: `MIT OR Apache-2.0` (see `LICENSE-MIT`/`LICENSE-APACHE`).',
        '',
        f'**{len(entries)} dependencies**, **{len(unknown)} with an unknown/unparseable license**'
        + (' (see below).' if unknown else '.'),
        '',
    ]
    if unknown:
        lines.append('## Unknown/unparseable license (explicit, not silently dropped)')
        lines.append('')
        for d in unknown:
            lines.append(f'- `{d["name"]} {d.get("version", "")}`')
        lines.append('')
    lines.append('## All dependencies')
    lines.append('')
    lines.append('| Crate | Version | License |')
    lines.append('| --- | --- | --- |')
    for e in entries:
        lines.append(f'| `{e["name"]}` | {e["version"]} | {e["license"]} |')
    lines.append('')
    (ROOT / 'docs' / 'LICENSE_INVENTORY.md').write_text('\n'.join(lines) + '\n')

    print(f'{len(entries)} dependencies, {len(unknown)} unknown-license')
    print('wrote docs/LICENSE_INVENTORY.md and target/dist/license-inventory.json')
    if unknown:
        print('WARNING: unknown-license dependencies present (see docs/LICENSE_INVENTORY.md)', file=sys.stderr)


if __name__ == '__main__':
    main()
